project:
  type: website
  output-dir: /

website:
  title: "Group 10 Crime Statistics"
  navbar:
    style: docked
    left:
      - href: index.qmd
        text: Home
      - href: 2022_map.html
        text: 2022 Map of U.S.
      - href: 2021_map.html
        text: 2021 Map of U.S.
format:
  html:
    theme: lux
    css: styles.css
    toc: true



