project:
  type: website
  output-dir: /

website:
  title: "crime-statistics"
  navbar:
    style: docked
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: map.html
        text: Map of U.S.

format:
  html:
    theme: lux
    css: styles.css
    toc: true



